sudo: true
# dist: trusty

language: python

python:
  - 2.7
  - 3.6

branches:
  only:
    - master

env:
   
before_install:
  - sudo apt-get install -y freeglut3-dev libglu1-mesa
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - git clone https://github.com/yxqd/dotmantid ~/.mantid

install:
  - export GIT_VER=`git describe --tags`
  - export VERSION=`git describe --tags | cut -d '-' -f1 | cut -c2-`
  - export VERSION_NEXT=`echo ${VERSION}| awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}'`
  - echo ${VERSION} ${VERSION_NEXT}
  - export _CONDA_PKG_VER=${VERSION_NEXT}.dev # conda pkg version to build
  - echo conda pkg version:${_CONDA_PKG_VER_}      git version:${GIT_VER}
  - ./travis/install.sh
  - source activate testenv
  
script:
  - py.test -s --cov=mantid2mcvine tests

after_success:
  - coveralls
  - source deactivate testenv
  - echo $TRAVIS_PYTHON_VERSION
  - if [ ${TRAVIS_PYTHON_VERSION:0:3} == "3.6" ]; then ./travis/create_conda_pkg.sh; fi

notifications:
  email:
    on_success: change
    on_failure: always
